version: '3.3'

services:
  db:
    build:
      context: ./Docker
      dockerfile: db.Dockerfile
    user: "1000:1000"
    image: postgres
    volumes:
      - ../postgres-data:/var/lib/postgresql/data
  web:
    build: .
    environment:
      DEBUG: 'True'
      DJANGO_SETTINGS_MODULE: 'p20.settings.local'
    command: sh -c "python p20/manage.py migrate && echo \"from django.contrib.auth import get_user_model;
        print('User already exists') if get_user_model().objects.filter(username='admin') else get_user_model().objects.create_superuser('admin', '', 'pass')\" |
        python p20/manage.py shell &&
        python p20/manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
    ports:
      - 8000:8000
    depends_on:
      - db
